name: 'Subset report'
on:
  pull_request:
    branches: [ master ]
    paths:
      - 'src/ontology/uberon-edit.obo'
  workflow_dispatch:
env:
  STATUS: 1
concurrency:
  group: environment-${{ github.ref }}
  # cancel-in-progress: true
jobs:
  is_changed:
    runs-on: macos-latest
    # container: obolibrary/odkfull:latest
    steps:
      - name: echo
        run : echo ${{ github.ref }}
      - name: Install docker - MacOS
        # if: env.STATUS == 1
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          brew install --cask docker
          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
          open -a /Applications/Docker.app --args --unattended --accept-license
          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
          docker --version
      # Checks-out current branch
      - uses: actions/checkout@v2
      - name: check path
        run: |
          pwd
          ls -l
      # Checks-out master and prepare git diff report
      - name: create git diff
        id: gitdiff
        if: ${{ github.event.pull_request.base.sha }}
        run: |
          echo ${{ github.sha }}
          echo ${{ github.event.pull_request.base.sha }}
          git fetch origin master ${{ github.event.pull_request.base.sha }}
          ls -l
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.sha }} src/ontology/uberon-edit.obo > gitdiff.md
          cat gitdiff.md
          echo ::set-output name=diff::$(cat gitdiff.md)
      # Set Status to 0 to cancel the workflow' if keyword not in the diff file
      - name: conditional cancel
        if: "!contains(steps.gitdiff.outputs.diff, 'in_taxon') && !contains(steps.gitdiff.outputs.diff, 'never_in_taxon') && !contains(steps.gitdiff.outputs.diff, 'only_in_taxon') && !contains(steps.gitdiff.outputs.diff, 'present_in_taxon')"
        run: |
          echo Taxon constraint updates do not exist
          echo "STATUS=0" >> $GITHUB_ENV
      # - uses: docker-practice/actions-setup-docker@1.0.9
      #   if: env.STATUS == 1
      # - name: docker test
      #   if: env.STATUS == 1
      #   run: |
      #     set -x
      #     docker version
      - name: Install ODK
        if: env.STATUS == 1
        run: docker pull obolibrary/odklite
        # Checks-out master branch under "master" directory
      - uses: actions/checkout@v2
        if: env.STATUS == 1
        with:
          ref: master
          path: master
      - name: make step for branch
        if: env.STATUS == 1
        run: cd src/ontology && mkdir -p tmp reports mirror && docker run -v $PWD/../../:/work -w /work/src/ontology -e ROBOT_JAVA_ARGS='-Xmx9G' -e JAVA_OPTS='-Xmx9G' --rm obolibrary/odklite make BRI=false MIR=false PAT=false IMP=false subsets/human-view.owl subsets/mouse-view.owl > TESTLOG.log
      - name: debugging branch
        if: ${{ failure() }}
        run: tail -20 src/ontology/TESTLOG.log
      - name: make step for master
        if: env.STATUS == 1
        run: cd master/src/ontology && mkdir -p tmp reports mirror && docker run -v $PWD/../../:/work -w /work/src/ontology -e ROBOT_JAVA_ARGS='-Xmx9G' -e JAVA_OPTS='-Xmx9G' --rm obolibrary/odklite make BRI=false MIR=false PAT=false IMP=false subsets/human-view.owl subsets/mouse-view.owl > TESTLOG.log
      - name: debugging master
        if: ${{ failure() }}
        run: tail -20 master/src/ontology/TESTLOG.log
      - name: prepare diff report
        if: env.STATUS == 1
        run: |
          cd src/ontology
          pwd
          docker run -v $PWD/../../:/work -w /work/src/ontology -e ROBOT_JAVA_ARGS='-Xmx9G' -e JAVA_OPTS='-Xmx9G' --rm obolibrary/odklite robot diff --left ../../master/src/ontology/subsets/human-view.owl --right subsets/human-view.owl -f markdown -o human-report.md
          docker run -v $PWD/../../:/work -w /work/src/ontology -e ROBOT_JAVA_ARGS='-Xmx9G' -e JAVA_OPTS='-Xmx9G' --rm obolibrary/odklite robot diff --left ../../master/src/ontology/subsets/mouse-view.owl --right subsets/mouse-view.owl -f markdown -o mouse-report.md
          ls -l
      - name: prepare comment
        if: env.STATUS == 1
        run: |
          ls -l src/ontology/
          echo "<details>   <summary> Here's a diff of your human-view </summary>   " > view-comment.md; cat src/ontology/human-report.md >> view-comment.md
          wc -l view-comment.md
          echo "</details><details>   <summary> Here's a diff of your mouse-view </summary>   " >> view-comment.md; cat src/ontology/mouse-report.md >> view-comment.md
          wc -l view-comment.md
          ls -l
      - name: post comment
        if: env.STATUS == 1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: NejcZdovc/comment-pr@v1.1.1
        with:
          file: "../../view-comment.md"
